# site settings
title: Metaphors for HRI
subtitle: Workshop @ ICSR 2020
email: place@holder.com
description: International Workshop held in conjunction with the 12th International Conference on Social Robotics (ICSR 2020). November 14, 2020. ONLINE
baseurl: "robotmetaphors.com" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# build settings
markdown: kramdown

sass:
  style: compressed
