# site settings
title: Metaphors for HRI
subtitle: Workshop @ ICSR 2020
email: place@holder.com
description: 1st International Workshop, held virtually and in conjunction with ICSR 2020.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6


# build settings
markdown: kramdown

sass:
  style: compressed
